# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAYAMI
subtitle: Vos projets web à Genève
email: contact@mayami.ch
description: Agence Web à Genève spécialisée dans le développement d'applications en Ruby on Rails.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mayami.ch" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer

sass:
  style: :compressed
