# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MAYAMI
email: contact@mayami.ch
description: noting
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Site titles

site.title: test
site.subtitle: test

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer

sass:
  style: :compressed
